/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { availabilityCheck } from "../../funcs/availabilityCheck.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$availabilityCheck: ToolDefinition = {
  name: "availability-check",
  description: `Check which operators and operations are currently available.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await availabilityCheck(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
