/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getAvailability } from "../../funcs/getAvailability.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$getAvailability: ToolDefinition = {
  name: "get-availability",
  description:
    `Get the payment (collection or disbursement) with the id specified`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await getAvailability(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
