/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymentsCollect } from "../../funcs/paymentsCollect.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.PaymentRequest$inboundSchema,
};

export const tool$paymentsCollect: ToolDefinition<typeof args> = {
  name: "payments-collect",
  description: `Collect a payment from a phone number.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await paymentsCollect(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
