/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymentsGet } from "../../funcs/paymentsGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetPaymentsIdRequest$inboundSchema,
};

export const tool$paymentsGet: ToolDefinition<typeof args> = {
  name: "payments-get",
  description:
    `Get the payment (collection or disbursement) with the specified ID.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await paymentsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
