/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { availabilityCheck } from "../funcs/availabilityCheck.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Availability extends ClientSDK {
  /**
   * Check which operators and operations are currently available.
   */
  async check(
    options?: RequestOptions,
  ): Promise<Array<components.Availability>> {
    return unwrapAsync(availabilityCheck(
      this,
      options,
    ));
  }
}
