/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymentsCollect } from "../funcs/paymentsCollect.js";
import { paymentsDisburse } from "../funcs/paymentsDisburse.js";
import { paymentsGet } from "../funcs/paymentsGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Payments extends ClientSDK {
  /**
   * Get the payment (collection or disbursement) with the specified ID.
   */
  async get(
    request: operations.GetPaymentsIdRequest,
    options?: RequestOptions,
  ): Promise<components.Payment> {
    return unwrapAsync(paymentsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Collect a payment from a phone number.
   */
  async collect(
    request: components.PaymentRequest,
    options?: RequestOptions,
  ): Promise<components.Payment> {
    return unwrapAsync(paymentsCollect(
      this,
      request,
      options,
    ));
  }

  /**
   * Disburse a payment from your balance to a phone number.
   */
  async disburse(
    request: components.PaymentRequest,
    options?: RequestOptions,
  ): Promise<components.Payment> {
    return unwrapAsync(paymentsDisburse(
      this,
      request,
      options,
    ));
  }
}
