/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Availability } from "./availability.js";
import { Payments } from "./payments.js";

export class Pay extends ClientSDK {
  private _payments?: Payments;
  get payments(): Payments {
    return (this._payments ??= new Payments(this._options));
  }

  private _availability?: Availability;
  get availability(): Availability {
    return (this._availability ??= new Availability(this._options));
  }
}
