/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @nkwa-pay/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx paymentsGet.ts
 */

import { Pay } from "@nkwa-pay/sdk";

const pay = new Pay({
  apiKeyAuth: process.env["PAY_API_KEY_AUTH"] ?? "",
});

async function main() {
  const result = await pay.get({
    id: "7112258c-4254-455f-a167-30549365ca9d",
  });

  console.log(result);
}

main().catch(console.error);
