workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    OpenAPI Plant Store:
        inputs:
            - location: ../../../Downloads/nkwa-pay-openapi.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/nkwa/pay/open-api-plant-store
targets:
    pay:
        target: typescript
        source: OpenAPI Plant Store
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/nkwa/pay/open-api-plant-store-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
