/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetPaymentsIdRequest = {
  /**
   * ID of payment to fetch
   */
  id: string;
};

/** @internal */
export const GetPaymentsIdRequest$inboundSchema: z.ZodType<
  GetPaymentsIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetPaymentsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetPaymentsIdRequest$outboundSchema: z.ZodType<
  GetPaymentsIdRequest$Outbound,
  z.ZodTypeDef,
  GetPaymentsIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPaymentsIdRequest$ {
  /** @deprecated use `GetPaymentsIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetPaymentsIdRequest$inboundSchema;
  /** @deprecated use `GetPaymentsIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetPaymentsIdRequest$outboundSchema;
  /** @deprecated use `GetPaymentsIdRequest$Outbound` instead. */
  export type Outbound = GetPaymentsIdRequest$Outbound;
}

export function getPaymentsIdRequestToJSON(
  getPaymentsIdRequest: GetPaymentsIdRequest,
): string {
  return JSON.stringify(
    GetPaymentsIdRequest$outboundSchema.parse(getPaymentsIdRequest),
  );
}

export function getPaymentsIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetPaymentsIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPaymentsIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPaymentsIdRequest' from JSON`,
  );
}
