/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const TelecomOperator = {
  Mtn: "mtn",
  Orange: "orange",
} as const;
export type TelecomOperator = ClosedEnum<typeof TelecomOperator>;

/** @internal */
export const TelecomOperator$inboundSchema: z.ZodNativeEnum<
  typeof TelecomOperator
> = z.nativeEnum(TelecomOperator);

/** @internal */
export const TelecomOperator$outboundSchema: z.ZodNativeEnum<
  typeof TelecomOperator
> = TelecomOperator$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TelecomOperator$ {
  /** @deprecated use `TelecomOperator$inboundSchema` instead. */
  export const inboundSchema = TelecomOperator$inboundSchema;
  /** @deprecated use `TelecomOperator$outboundSchema` instead. */
  export const outboundSchema = TelecomOperator$outboundSchema;
}
